// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA03ehm3pyzPi2RZvlbuJZwNShnVrUzm60',
    appId: '1:863422546089:web:384791751499e421a529b8',
    messagingSenderId: '863422546089',
    projectId: 'gromy-ps',
    authDomain: 'gromy-ps.firebaseapp.com',
    storageBucket: 'gromy-ps.firebasestorage.app',
    measurementId: 'G-9Z0F50SWT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfQDXZI5oVyzmpICfsFgCu6E5jMSRhMs0',
    appId: '1:863422546089:android:e494c355895486b8a529b8',
    messagingSenderId: '863422546089',
    projectId: 'gromy-ps',
    storageBucket: 'gromy-ps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLlgyG3QUOJvj1vM8HtUUojZdoXv3mjWs',
    appId: '1:863422546089:ios:80360643d7b03fe8a529b8',
    messagingSenderId: '863422546089',
    projectId: 'gromy-ps',
    storageBucket: 'gromy-ps.firebasestorage.app',
    androidClientId: '863422546089-gvtds0adct95cfgvvda1lqjm82kvl8eu.apps.googleusercontent.com',
    iosClientId: '863422546089-608jhse783jlaadeo40sedn2u51oeipv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gromy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLlgyG3QUOJvj1vM8HtUUojZdoXv3mjWs',
    appId: '1:863422546089:ios:80360643d7b03fe8a529b8',
    messagingSenderId: '863422546089',
    projectId: 'gromy-ps',
    storageBucket: 'gromy-ps.firebasestorage.app',
    androidClientId: '863422546089-gvtds0adct95cfgvvda1lqjm82kvl8eu.apps.googleusercontent.com',
    iosClientId: '863422546089-608jhse783jlaadeo40sedn2u51oeipv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gromy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA03ehm3pyzPi2RZvlbuJZwNShnVrUzm60',
    appId: '1:863422546089:web:b46d903c9dbdeb94a529b8',
    messagingSenderId: '863422546089',
    projectId: 'gromy-ps',
    authDomain: 'gromy-ps.firebaseapp.com',
    storageBucket: 'gromy-ps.firebasestorage.app',
    measurementId: 'G-J7T0JXD215',
  );
}
