/// Flutter icons MyFlutterApp
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MisIconos.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MisIconos';
  static const String? _kFontPkg = null;

  static const IconData logo_gromy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class IconPack1 {
  IconPack1._();

  static const _kFontFam = 'IconPack1';
  static const String? _kFontPkg = null;

  static const IconData award = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_plus = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crown_minus = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy_1 = IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
